
import { Button, Link, Navbar, NavbarBrand, NavbarContent, NavbarItem, NextUIProvider } from "@nextui-org/react";
import "./globals.css"

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className="h-screen">
				<NextUIProvider>
					<Navbar>
						<NavbarBrand>
							<p className='font-bold text-inherit'>HYPERLOOP</p>
						</NavbarBrand>
						<NavbarContent className='hidden sm:flex gap-4' justify='center'>
							<NavbarItem>
								<Link color='foreground' href='#'>
									Features
								</Link>
							</NavbarItem>
							<NavbarItem isActive>
								<Link href='#' aria-current='page'>
									Customers
								</Link>
							</NavbarItem>
							<NavbarItem>
								<Link color='foreground' href='#'>
									Integrations
								</Link>
							</NavbarItem>
						</NavbarContent>
						<NavbarContent justify='end'>
						</NavbarContent>
					</Navbar>
					<main className='container mx-auto px-8 pt-4 h-full'>
					{children}
					</main>
				</NextUIProvider>
			</body>
		</html>
	);
}
