import { NextUIProvider } from '@nextui-org/react';
import { Content } from '@/components/navigation/content';
import { Sidebar } from '@/components/navigation/sidebar';

import './globals.css';

export const metadata = {
	title: 'Hyperloop',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body>
				<NextUIProvider>
					<div className='bg-gray-100 h-dvh'>
						<Sidebar />
						<div className='h-full ml-auto mb-6 lg:w-[75%] xl:w-[80%] 2xl:w-[85%]'>
							<Content>{children}</Content>
						</div>
					</div>
				</NextUIProvider>
			</body>
		</html>
	);
}
